### ISSUE TITLE
Unknown flag: --wf

### ISSUE THREAD

**Issue by FabianGD** [sheepforce/Exckel#3]
Directly after building and installing Exckel from source, I tried a first example run for my data by specifying everything according to the Benzene sample (see README.md).

However, I immediately got the response (after the nice banner, btw) that the "--wf" flag was unknown to the system. This seems like a bug to me.

**Comment by sheepforce** [comment]
You are right, the example is outdated, but i think it is not a bug. Recently i updated exckel to support arbitrary data to tabulate. This led to splitting exckel in 2 modes. For the analysing excited state data, the call is now `exckel exckel [args]`, while the other mode is obtained as `exckel tabulate [args]`.
I will update the readme.
